### ISSUE TITLE
GameControlPlugin.lplug4 is not in the repo, and there are no releases

### ISSUE THREAD

**Issue by Kaurin** [Thx1010saascas/GameControlPlugin#1]
Hi,

I just got the Loupedeck and would like to try out your plugin. Unfortunately, I can't find the GameControlPlugin.lplug4 in this repo or in releases.

P.S. I have some experience in setting up Github Actions and would be willing to donate my time to help you with builds.

Cheers!

**Comment by Thxsoft64** [comment]
G'day, so you can't see it in https://github.com/Thx1010saascas/GameControlPlugin/releases/tag/0.6 ?
I can see it in a private window without being logged in at all.

I have a code build in a different branch that lets us specify the axis in the config instead of having lots of different actions to choose from. IE: There are now two axis actions instead of maybe 12. If I can update the docs tonight I'll publish that one. It is a bit cleaner.

**Comment by Kaurin** [comment]
Ah, I didn't even click releases because they weren't showing anything from the front page, apologies.

**Comment by Thxsoft64** [comment]
No worries. I've not used github before so I'm not that sure of what I'm doing with it or what it can do.
I just published an update that reduces a lot of code and using it a bit cleaner, IMHO :-)

The wiki has some new useful info. I will probably replace all the original doco with an updated wiki at some point. I think it may be tough for non-technical people to use well.  Especially if you are like me and didn't know how to use a loupedeck either!
